### ISSUE TITLE
426 Transfer aborted. Interrupted system call

### ISSUE THREAD

**Issue by notlebowski** [proftpd/proftpd#774]
The behaviour is similar to https://github.com/proftpd/proftpd/issues/615
The big difference is that it's NOT happening with Filezilla and it's version 1.3.6

I have several Plesk servers as a hosting provider and none of my clients complain about FTP.
We also have 12 3CX-servers (3 Windows & 9 Linux) in the field and they are configured to backup their config with FTP. This was all working fine for all of these servers.
Then I noticed none of the backups came through and the last backup was at May 7 2018 for all these servers.
That day I upgraded Plesk.
Plesk must have also upgraded ProFTPd as it was running version 1.3.6 that was built on Feb 20 2018.

All tests with Filezilla run fine, but none of the 3CX-servers are able to backup since then. 2 of the Windows 3CX-servers don't receive upgrades, so the only change was our server. I also tried another Plesk server of ours, but I'm having the same.

More people have a problem with their 3CX-backup, but I don't know if this is also linked to ProFTPd.

https://talk.plesk.com/threads/3cx-ftp-backups-fails-since-upgrading-to-17-8.348278/
```
220 ProFTPD Server (ProFTPD) [xx.xx.xx.xx]
USER blabla
331 Password required for blabla
PASS secret
230 User blabla logged in
FEAT
211-Features:
AUTH TLS
CCC
CLNT
EPRT
EPSV
HOST
LANG en-US*
MDTM
MFF modify;UNIX.group;UNIX.mode;
MFMT
MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;
PBSZ
PROT
REST STREAM
SIZE
SSCN
TVFS
UTF8
211 End
OPTS UTF8 ON
200 UTF8 set to on
TYPE I
200 Type set to I
SIZE /httpdocs/folder/backup.zip
550 /httpdocs/folder/backup.zip: No such file or directory
EPSV
501 EPSV: Operation not permitted
PASV
227 Entering Passive Mode (xx,xx,xxx,xx,194,130).
STOR /httpdocs/folder/backup.zip
150 Opening BINARY mode data connection for /httpdocs/folder/backup.zip
(client sends data)
426 Transfer aborted. Interrupted system call
```

### ProFTPD Version and Configuration
```
proftpd -V
Compile-time Settings:
  Version: 1.3.6 (stable)
  Platform: LINUX [Linux 4.13.0-41-generic x86_64]
  Built: Tue Feb 20 2018 17:32:25 +07
  Built With:
    configure  '--with-modules=mod_ratio:mod_readme:mod_quotatab:mod_quotatab_file:mod_tls' '--enable-nls' '--enable-auth-pam' '--enable-ncurses' '--enable-ipv6' '--enable-buffer-size=8192' '--prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--libexecdir=/usr/lib' '--datadir=/usr/share' '--sysconfdir=/etc' '--sharedstatedir=/usr/com' '--localstatedir=/var' '--libdir=/usr/lib/x86_64-linux-gnu' '--includedir=/usr/include' '--infodir=/usr/share/info' '--mandir=/usr/share/man' '--build=x86_64-linux-gnu' '--host=x86_64-linux-gnu' 'build_alias=x86_64-linux-gnu' 'host_alias=x86_64-linux-gnu' 'CC=gcc' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXX=g++' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'

  CFLAGS: -g2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic
  LIBS:  -lssl -lcrypto -L$(top_srcdir)/lib/libcap -lcap  -lssl -lcrypto  -lpam -lsupp -lattr -lcrypt -ldl

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /var/proftpd.pid
    Scoreboard File:
      /var/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    - Controls support
    + curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncurses support
    + NLS support
    - Redis support
    - Sodium support
    + OpenSSL support
    - PCRE support
    - POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 8192
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

**Comment by kdesjard** [comment]
I'm pretty sure this was fixed after 1.3.6 in:

Bug #4319: Treat EINTR like EAGAIN

https://github.com/proftpd/proftpd/commit/f09f0c661621eb22cb1ce579194478007ba62866

I was having the same issue until I built proftpd with a version between 1.3.6 and HEAD (before SSL changes).

**Comment by eugenepaniot** [comment]
Have the same issue in Oracle Solaris 11.4.5.3.0:

```
# pkg info ftp
             Name: network/ftp
          Summary: FTP client command
      Description: The ftp(1) command is the user interface to the Internet
                   standard File Transfer Protocol (FTP) (RFC 959), which can be
                   used to transfer files to and from a remote network site.
         Category: Applications/System Utilities
            State: Installed
        Publisher: solaris
          Version: 11.4
           Branch: 11.4.5.0.1.3.0
   Packaging Date: December 20, 2018 at  8:01:59 AM
Last Install Time: March  5, 2019 at 11:40:55 AM
             Size: 280.96 kB
             FMRI: pkg://solaris/network/ftp@11.4-11.4.5.0.1.3.0:20181220T080159Z

             Name: service/network/ftp
          Summary: FTP Server and Utilities
         Category: System/Core
            State: Installed
        Publisher: solaris
          Version: 1.3.6
           Branch: 11.4.3.0.1.4.0
   Packaging Date: October 24, 2018 at  9:48:59 PM
Last Install Time: March  5, 2019 at 11:40:55 AM
             Size: 4.34 MB
             FMRI: pkg://solaris/service/network/ftp@1.3.6-11.4.3.0.1.4.0:20181024T214859Z
      Project URL: http://www.proftpd.org/
       Source URL: https://github.com/proftpd/proftpd/archive/v1.3.6.zip
```

**Comment by Whitefox98** [comment]
Same here with ProFTPD Version 1.3.6

**Comment by notlebowski** [comment]
still the same... 

# proftpd -V
Compile-time Settings:
  Version: 1.3.6c (maint)
  Platform: LINUX [Linux 4.13.0-41-generic x86_64]
  Built: Wed Mar 11 2020 13:35:27 +07
  Built With:
    configure  '--docdir=/usr/share/doc/psa-proftpd' '--infodir=/usr/share/info' '--localedir=/usr/share/locale' '--exec-prefix=/usr' '--sysconfdir=/etc' '--includedir=/usr/include' '--prefix=/usr' '--libdir=/usr/lib/x86_64-linux-gnu' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--sharedstatedir=/usr/com' '--libexecdir=/usr/libexec/proftpd' '--mandir=/usr/share/man' '--bindir=/usr/bin' '--localstatedir=/var' '--build=x86_64-linux-gnu' '--host=x86_64-linux-gnu' '--enable-dso' '--with-modules=mod_ratio:mod_readme:mod_quotatab:mod_quotatab_file:mod_tls' '--enable-nls' '--enable-auth-pam' '--enable-ncurses' '--enable-ipv6' '--enable-buffer-size=8192' 'build_alias=x86_64-linux-gnu' 'host_alias=x86_64-linux-gnu' 'CC=ccache /usr/bin/gcc' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--enable-new-dtags ' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CPP=/usr/bin/cpp' 'CXX=ccache /usr/bin/g++' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'

  CFLAGS: -g2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--enable-new-dtags  -rdynamic
  LIBS:  -lssl -lcrypto -lcap  -lssl -lcrypto  -lpam -lsupp -lattr -lcrypt -ldl

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /var/proftpd.pid
    Scoreboard File:
      /var/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    - Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncurses support
    + NLS support
    - Redis support
    - Sodium support
    + OpenSSL support
    - PCRE support
    - POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 8192
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

**Comment by Castaglia** [comment]
@notlebowski can you provide [debug logging](http://www.proftpd.org/docs/howto/Debugging.html) from one of these failed transfers?  And the full `proftpd.conf` you're using?  I'm hoping to reproduce these issues locally.  Thanks!

**Comment by notlebowski** [comment]
My statement wasn't true...
Just like it stopped working 2 years ago, it started working again some time ago. Probably after an update of Plex which contained a newer version of ProFTPd.

**Comment by Castaglia** [comment]
@notlebowski OK, thanks for the update.  Mind if I close this ticket, then?  I'll assume that this was related to [Bug #4319](http://bugs.proftpd.org/show_bug.cgi?id=4319).

**Comment by Whitefox98** [comment]
@Castaglia Where is the solution? What version should we use for that be solved?

**Comment by Castaglia** [comment]
@Whitefox98 per [Bug #4319](http://bugs.proftpd.org/show_bug.cgi?id=4319), using 1.3.6a (or later), or 1.3.7rc1 (or later) should work.

**Comment by Whitefox98** [comment]
1.3.7rc1 dosen't works but 1.3.7rc4 for me yes!

**Comment by notlebowski** [comment]
I am dependent of the ProFTPd that Plesk provides. The FTP transfers that 3CX (phone software) made for their backup were working fine until I received an update of ProFTPd in May 2018 to 1.3.6

Each night these transfers kept trying and failed. 
This year (2020) Plesk provided a ProFTPd with version 1.3.6c and these backups started working again.

**Comment by notlebowski** [comment]
I went into the mail-reports of the 3CX back-ups and noticed the first successful transfer on 23-10-2019 of a certain 3CX. However... another 3CX only had its first successful transfer on 8-11-2019. All previous transfers of that client failed.

This means that **NOT** a change of the ProFTPd server changed the behaviour, but more probably an update of 3CX, meaning the FTP-client.

@Whitefox98 notices a change between 1.3.7rc1 and 1.3.7rc4. 
My latest ProFTPd is version 1.3.6c

**Comment by azurit** [comment]
Any workaround for 1.3.6? I cannot update.

**Comment by sena73** [comment]
> Any workaround for 1.3.6? I cannot update.
> 
> EDIT: Also downgrade isn't possible. This bug is present in ProFTPd package in Debian Buster. :(

Workaround: download and compile proftpd package from Debian testing. Just download 3 files:
[proftpd-dfsg_1.3.7a+dfsg-12.dsc](http://deb.debian.org/debian/pool/main/p/proftpd-dfsg/proftpd-dfsg_1.3.7a+dfsg-12.dsc), [proftpd-dfsg_1.3.7a+dfsg.orig.tar.gz](http://deb.debian.org/debian/pool/main/p/proftpd-dfsg/proftpd-dfsg_1.3.7a+dfsg.orig.tar.gz), [proftpd-dfsg_1.3.7a+dfsg-12.debian.tar.xz](http://deb.debian.org/debian/pool/main/p/proftpd-dfsg/proftpd-dfsg_1.3.7a+dfsg-12.debian.tar.xz), then
 unpack:
`dpkg-source -x proftpd-dfsg_1.3.7a+dfsg-12.dsc`
`cd proftpd-dfsg-1.3.7a+dfsg`
`vim debian/control` # replace `debhelper-compat (=13)` to `debhelper-compat (=12)`
Install dependencies
`sudo apt install dh-exec libacl1-dev libcap-dev default-libmysqlclient-dev unixodbc-dev libgeoip-dev libmemcached-dev debhelper-compat libhiredis-dev libsodium-dev libmd-dev build-essential debhelper devscripts`
then build:
`debuild -uc -us`

**Comment by mivk** [comment]
On Debian 10 "Buster", I could install version 1.3.7c from Debian testing ("Bookworm"). That seems to have fixed the problem. There is no need to compile from source. This is what worked for me:

```bash
c=us # adapt to your country for the deb mirror
wget http://ftp.$c.debian.org/debian/pool/main/p/proftpd-dfsg/proftpd-basic_1.3.7c%2Bdfsg-1_all.deb \
 http://ftp.$c.debian.org/debian/pool/main/p/proftpd-dfsg/proftpd-core_1.3.7c%2Bdfsg-1_amd64.deb \
 http://ftp.$c.debian.org/debian/pool/main/p/proftpd-dfsg/proftpd-doc_1.3.7c%2Bdfsg-1_all.deb \
 http://ftp.$c.debian.org/debian/pool/main/p/proftpd-dfsg/proftpd-mod-crypto_1.3.7c%2Bdfsg-1_amd64.deb \
 http://ftp.$c.debian.org/debian/pool/main/p/proftpd-dfsg/proftpd-mod-sqlite_1.3.7c%2Bdfsg-1_amd64.deb \
 http://ftp.$c.debian.org/debian/pool/main/p/proftpd-dfsg/proftpd-mod-wrap_1.3.7c%2Bdfsg-1_amd64.deb \
 http://ftp.$c.debian.org/debian/pool/main/libx/libxcrypt/libcrypt1_4.4.18-4_amd64.deb

# I had to remove IdentLookups from my config:
perl -i.bak -pe 's/^(\s*)(IdentLookups)/$1# $2/i' /etc/proftpd/proftpd.conf

dpkg -i *.deb
```

**Comment by Castaglia** [comment]
If there's nothing more to add to this ticket, I'd like to close it.
